[package]
name = "riscv64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
byteorder = "1.5.0"
elf = "0.7.4"
nix = "0.29.0"
residua-uleb128 = "0.2.0"
thiserror = "1.0.63"
